var data=[
    {
    "id": 8,
    "cid": 7,
    "code": "P001",
    "title": "Bàn tiếp khách",
    "description": "<p>B&agrave;n tiếp kh&aacute;ch</p>\n",
    "content": "<p>B&agrave;n tiếp kh&aacute;ch</p>\n",
    "image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
    "metaTitle": "Bàn tiếp khách",
    "metaKeyword": "Bàn tiếp khách",
    "metaDescription": "Bàn tiếp khách",
    "slug": "ban-tiep-khach",
    "priceOld": 12999000,
    "priceNew": 9999000,
    "size": "Size vừa",
    "views": 0,
    "likes": 0,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2020-07-27T00:00:00",
    "updatedDate": "2020-07-27T17:27:50.89",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": null
    },
    {
    "id": 9,
    "cid": 7,
    "code": "P002",
    "title": "Bàn uống nước 1",
    "description": "<p>B&agrave;n uống nước với thiết kế sang trọng, m&agrave;",
    "content": "<h1>B&Agrave;N UỐNG NƯỚC - B&Agrave;N TR&Agrave; CAO CẤP CHO",

    "image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
    "metaTitle": "Bàn uống nước",
    "metaKeyword": "Bàn uống nước, bàn trà, bàn uống nước chung cư, bàn trà",

"slug": "ban-uong-nuoc",
"priceOld": 8999000,
"priceNew": 8999000,
"size": "4 ngăn",
"views": 0,
"likes": 0,
"star": null,
"home": null,
"hot": 1,
"createdDate": "2020-08-26T00:00:00",
"updatedDate": "2020-08-26T18:53:29.497",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": null
},
{
"id": 10,
"cid": 8,
"code": "P003",
"title": "Giường hộp ",
"description": "<p>Giường hộp thiết kế sang trọng tiện &iacute;ch</p>\n",
"content": "<p>Giường hộp thiết kế sang trọng tiện &iacute;ch</p>\n",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Giường hộp thiết kế sang trọng tiện ích",
"metaKeyword": "Giường hộp thiết kế sang trọng tiện ích",
"metaDescription": "Giường hộp thiết kế sang trọng tiện ích",
"slug": "giuong-hop-thiet-ke-sang-trong-tien-ich",
"priceOld": 8999000,
"priceNew": 8999000,
"size": null,
"views": 0,
"likes": 0,
"star": null,
"home": 0,
"hot": null,
"createdDate": "2020-07-28T00:00:00",
"updatedDate": "2020-07-28T10:43:56.717",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": null
},
{"id": 11,
"cid": 10,
"code": "P005",
"title": "Bàn ăn nhà bếp",
"description": "<p>B&agrave;n ăn nh&agrave; bếp sang trọng</p>\n",
"content": "<p>B&agrave;n ăn nh&agrave; bếp sang trọng</p>\n",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Bàn ăn nhà bếp sang trọng",
"metaKeyword": "Bàn ăn nhà bếp sang trọng",
"metaDescription": "Bàn ăn nhà bếp sang trọng",
"slug": "ban-an-nha-bep-sang-trong",
"priceOld": 9870000,
"priceNew": 9899000,
"size": null,
"views": 0,
"likes": 0,
"star": null,
"home": 0,
"hot": null,
"createdDate": "2020-07-28T00:00:00",
"updatedDate": "2020-07-28T10:42:43.207",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": null
},
{
"id": 12,
"cid": 7,
"code": "P006",
"title": "Bàn uống nước 2",
"description": "<p>B&agrave;n uống nước 2</p>\n",
"content": "<p>B&agrave;n uống nước 2</p>\n",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "BÀN UỐNG NƯỚC 2",
"metaKeyword": "Bàn uống nước 2",
"metaDescription": "Bàn uống nước 2\n",
"slug": "ban-uong-nuoc-2",
"priceOld": 3999000,
"priceNew": 3999000,
"size": "Size vừa",
"views": 0,
"likes": 0,
"star": null,
"home": null,
"hot": 1,
"createdDate": "2020-07-31T00:00:00",
"updatedDate": "2020-07-31T00:49:13.867","adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": null
},
{
"id": 13,
"cid": 7,
"code": "P007",
"title": "Kệ để đồ",
"description": "<p>Kệ để đồ</p>\n",
"content": "<p>Kệ để đồ</p>\n",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Kệ để đồ",
"metaKeyword": "Kệ để đồ",
"metaDescription": "Kệ để đồ\n",
"slug": "ke-de-do",
"priceOld": 15999000,
"priceNew": 12999000,
"size": "4 ngăn",
"views": 0,
"likes": 0,
"star": null,
"home": null,
"hot": 1,
"createdDate": "2020-07-31T00:00:00",
"updatedDate": "2020-07-31T00:50:56.44",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": null
},
{
"id": 14,
"cid": 7,
"code": "P008",
"title": "Kệ TV",
"description": "<p>Kệ TV</p>\n",
"content": "<p>Kệ TV</p>\n",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Kệ TV",
"metaKeyword": "Kệ TV",
"metaDescription": "Kệ TV\n",
"slug": "ke-tv",
"priceOld": 15999000,
"priceNew": 12899000,
"size": "4 ngăn",
"views": 0,"likes": 0,
"star": null,
"home": null,
"hot": 1,
"createdDate": "2020-07-31T00:50:35.453",
"updatedDate": "2020-07-31T00:50:35.453",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": null
},
{
"id": 15,
"cid": 8,
"code": "P009",
"title": "Tủ quần áo",
"description": "<p>Tủ quần &aacute;o</p>\n",
"content": "<p>Tủ quần &aacute;o</p>\n",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Tủ quần áo",
"metaKeyword": "Tủ quần áo",
"metaDescription": "Tủ quần áo\n",
"slug": "tu-quan-ao",
"priceOld": 15999000,
"priceNew": 12999000,
"size": "4 ngăn, trắng, gỗ",
"views": 0,
"likes": 0,
"star": null,
"home": null,
"hot": 1,
"createdDate": "2020-07-31T00:55:32.307",
"updatedDate": "2020-07-31T00:55:32.307",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": null
},
{
"id": 17,
"cid": 8,
"code": "P010",
"title": "Giường gỗ",
"description": "<p>Giường gỗ</p>\n",
"content": "<p>Giường gỗ</p>\n",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Giường gỗ",
"metaKeyword": "Giường gỗ","metaDescription": "Giường gỗ\n",
"slug": "giuong-go",
"priceOld": 20999000,
"priceNew": 18999000,
"size": "Size vừa",
"views": 0,
"likes": 0,
"star": null,
"home": null,
"hot": 1,
"createdDate": "2020-07-31T00:00:00",
"updatedDate": "2020-07-31T01:15:39.39",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": null
},
{
"id": 18,
"cid": 8,
"code": "P011",
"title": "Kệ đầu giường",
"description": "<p>Kệ đầu giường</p>\n",
"content": "<p>Kệ đầu giường</p>\n",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Kệ đầu giường",
"metaKeyword": "Kệ đầu giường",
"metaDescription": "Kệ đầu giường\n",
"slug": "ke-dau-giuong",
"priceOld": 20899000,
"priceNew": 18899000,
"size": "2 ngăn",
"views": 0,
"likes": 0,
"star": null,
"home": null,
"hot": 1,
"createdDate": "2020-07-31T00:00:00",
"updatedDate": "2020-07-31T01:16:27.333",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": null
},
{
"id": 19,
"cid": 8,
"code": "P012","title": "Giường châu âu",
"description": "<h1>GIƯỜNG NGỦ T&Acirc;N CỔ ĐIỂN</h1>\n\n<p>Đối với",

"content": "<h1>GIƯỜNG NGỦ T&Acirc;N CỔ ĐIỂN</h1>\n\n<p>Đối với kh&ocirc;ng",

"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg","metaTitle": "Giường châu âu giá tốt tại hà nội",
"metaKeyword": "Giường châu âu",
"metaDescription": "GIƯỜNG NGỦ TÂN CỔ ĐIỂN\n\nĐối với không gian phòng ngủ",

"slug": "giuong-chau-au-gia-tot",
"priceOld": 25999000,
"priceNew": 22999000,
"size": "Size vừa",
"views": 0,
"likes": 0,
"star": null,
"home": null,
"hot": 1,
"createdDate": "2020-08-10T00:00:00",
"updatedDate": "2020-08-10T14:58:46.003",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": null
},
{
"id": 20,
"cid": 7,
"code": "P013",
"title": "SOFA",
"description": "SOFA",
"content": "SOFA",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "SOFA",
"metaKeyword": "SOFA",
"metaDescription": "SOFA",
"slug": "sofa",
"priceOld": 10000000,
"priceNew": 8400000,
"size": null,
"views": null,
"likes": null,
"star": null,
"home": 0,
"hot": null,
"createdDate": "2023-09-30T16:24:25.493",
"updatedDate": "2023-09-30T16:24:25.493",
"adminCreated": "4",
"adminUpdated": "4","status": 1,
"isdelete": false
},
{
"id": 21,
"cid": 7,
"code": "P014",
"title": "Bàn trà",
"description": "Bàn trà",
"content": "Bàn trà",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Bàn trà",
"metaKeyword": "Bàn trà",
"metaDescription": "Bàn trà",
"slug": null,
"priceOld": 25999000,
"priceNew": 22999000,
"size": null,
"views": null,
"likes": null,
"star": null,
"home": 0,
"hot": null,
"createdDate": "2023-09-30T16:28:22.943",
"updatedDate": "2023-09-30T16:28:22.943",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": false
},
{
"id": 22,
"cid": 11,
"code": "P015",
"title": "Bồn rửa mặt",
"description": "Bồn rửa mặt",
"content": "Bồn rửa mặt",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Bồn rửa mặt",
"metaKeyword": "Bồn rửa mặt",
"metaDescription": "Bồn rửa mặt",
"slug": null,
"priceOld": 8500000,
"priceNew": 8000000,
"size": null,
"views": null,
"likes": null,
"star": null,"home": 0,
"hot": null,
"createdDate": "2023-09-30T16:43:15.333",
"updatedDate": "2023-09-30T16:43:15.333",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": false
},
{
"id": 23,
"cid": 11,
"code": "P016",
"title": "Bồn rừa tay",
"description": "Bồn rừa tay",
"content": "Bồn rừa tay",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Bồn rừa tay",
"metaKeyword": "Bồn rừa tay",
"metaDescription": "Bồn rừa tay",
"slug": "bon-rua-tay",
"priceOld": 3950000,
"priceNew": 3900000,
"size": null,
"views": null,
"likes": null,
"star": null,
"home": 0,
"hot": null,
"createdDate": "2023-09-30T16:44:40.917",
"updatedDate": "2023-09-30T16:44:40.917",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": false
},
{
"id": 24,
"cid": 11,
"code": "P017",
"title": "Tủ âm tường",
"description": "Tủ âm tường",
"content": "Tủ âm tường",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Tủ âm tường",
"metaKeyword": "Tủ âm tường",
"metaDescription": "Tủ âm tường",
"slug": "tu-am-tuong-p017","priceOld": 9500000,
"priceNew": 8900000,
"size": null,
"views": null,
"likes": null,
"star": null,
"home": 0,
"hot": null,
"createdDate": "2023-09-30T16:46:15.97",
"updatedDate": "2023-09-30T16:46:15.97",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": false
},
{
"id": 25,
"cid": 11,
"code": "P018",
"title": "Bồn rửa 2",
"description": "Bồn rửa 2",
"content": "Bồn rửa 2",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Bồn rửa 2",
"metaKeyword": "Bồn rửa 2",
"metaDescription": "Bồn rửa 2",
"slug": "bon-rua-2-p018",
"priceOld": 4000000,
"priceNew": 3300000,
"size": null,
"views": null,
"likes": null,
"star": null,
"home": 0,
"hot": null,
"createdDate": "2023-09-30T16:46:59.757",
"updatedDate": "2023-09-30T16:46:59.757",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": false
},
{
"id": 26,
"cid": 12,
"code": "P019",
"title": "Giường tầng",
"description": "Giường tầng","content": "Giường tầng",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Giường tầng",
"metaKeyword": "Giường tầng",
"metaDescription": "Giường tầng",
"slug": "giuong-tang-p019",
"priceOld": 11000000,
"priceNew": 9800000,
"size": null,
"views": null,
"likes": null,
"star": null,
"home": 0,
"hot": null,
"createdDate": "2023-09-30T16:50:35.72",
"updatedDate": "2023-09-30T16:50:35.72",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": false
},
{
"id": 27,
"cid": 12,
"code": "P020",
"title": "Bàn học",
"description": "Bàn học",
"content": "Bàn học",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Bàn học",
"metaKeyword": "Bàn học",
"metaDescription": "Bàn học",
"slug": "ban-hoc-p020",
"priceOld": 3500000,
"priceNew": 3000000,
"size": null,
"views": null,
"likes": null,
"star": null,
"home": 0,
"hot": null,
"createdDate": "2023-09-30T16:51:20.29",
"updatedDate": "2023-09-30T16:51:20.29",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": false
},{
    "id": 28,
    "cid": 13,
    "code": "P021",
    "title": "Ghế văn phòng",
    "description": "Ghế văn phòng",
    "content": "Ghế văn phòng",
    "image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
    "metaTitle": "Ghế văn phòng",
    "metaKeyword": "Ghế văn phòng",
    "metaDescription": "Ghế văn phòng",
    "slug": "ghe-van-phong-p021",
    "priceOld": 6000000,
    "priceNew": 5700000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T16:58:15.04",
    "updatedDate": "2023-09-30T16:58:15.04",
    "adminCreated": "4",
    "adminUpdated": "4",
    "status": 1,
    "isdelete": false
    },
    {
    "id": 29,
    "cid": 15,
    "code": "P022",
    "title": "Đèn chùm",
    "description": "Đèn chùm",
    "content": "Đèn chùm",
    "image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
    "metaTitle": "Đèn chùm",
    "metaKeyword": "Đèn chùm",
    "metaDescription": "Đèn chùm",
    "slug": "den-chum-p022",
    "priceOld": 5300000,
    "priceNew": 4300000,
    "size": null,
    "views": null,
    "likes": null,
    "star": null,
    "home": 0,
    "hot": null,
    "createdDate": "2023-09-30T17:00:32.483","updatedDate": "2023-09-30T17:00:32.483",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": false
},
{
"id": 30,
"cid": 14,
"code": "P023",
"title": "Cầu thang",
"description": "Cầu thang",
"content": "Cầu thang",
"image": "img/giuong-ngu-chau-Au-hoang-gia.jpg",
"metaTitle": "Cầu thang",
"metaKeyword": "Cầu thang",
"metaDescription": "Cầu thang",
"slug": "cau-thang-p023",
"priceOld": 35000000,
"priceNew": 30000000,
"size": null,
"views": null,
"likes": null,
"star": null,
"home": 0,
"hot": null,
"createdDate": "2023-09-30T17:08:24.57",
"updatedDate": "2023-09-30T17:08:24.57",
"adminCreated": "4",
"adminUpdated": "4",
"status": 1,
"isdelete": false
},
]

function renderCart() {
    let cartContainer = $("#product");
    cartContainer.empty(); // Đã sửa lỗi chính tả
    data.forEach(item => {
      let productHtml = `
              <div class="col mb-4">
              <div class="card mt-4">
                <img src="${item.image}" class="card-img-top">
                <div class="card-body text-center">
                  <h5 class="card-title text-primary-emphasis">${item.title}</h5>
                  <p class="card-price"> Giá: ${item.priceNew}<sup class="text-danger">đ</sup></p>
                </div>
              </div>
            </div>
      `;
      cartContainer.append(productHtml);
    });
  }
  
  $(document).ready(function() {
    renderCart();
  });